name: Run Bot Every 30 Minutes

on:
  schedule:
    - cron: "*/30 * * * *"  # Runs every 30 minutes
  workflow_dispatch:       # Allows manual triggering

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: v18  # Specify your Node.js version

      # Install dependencies
      - name: Install Dependencies
        run: npm ci


      # Load environment variables from GitHub Secrets
      - name: Set environment variables
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          USER_DATA: ${{ secrets.USER_DATA }}
          URLS: ${{ secrets.URLS }}
          HEADLESS_MODE: ${{ secrets.HEADLESS_MODE }}
        run: |
          echo "TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN" >> .env
          echo "HEADER=$HEADER" >> .env
          # For testing: print env vars (comment/remove in production)
          echo "Environment variables set."
          echo "TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN"
          echo "USER_DATA=$USER_DATA"
          
      # Run the bot
      - name: Run Bot
        run: node --trace-warnings index.js

