name: Run Bot Every 1 Minutes

on:
  schedule:
    - cron: "*/1 * * * *"  # Runs every 1 minutes

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: v23.2.0

      - name: Install Dependencies
        run: |
          npm install

      - name: Run Bot
        run: |
          node index.js
